<?php

namespace app\models;

use yii\db\ActiveQuery;

class BooksQuery extends ActiveQuery
{
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    public function getTopTenAuthorsForYear($year = 2023)
    {
        return $this
            ->select([
                'author_id',
                'count(*) books_count'
            ])
            ->where([
                '=', 'year', $year
            ])
            ->groupBy([
                'author_id'
            ])
            ->orderBy([
                'books_count' => SORT_DESC
            ])
            ->all();
    }
}